<?php

namespace App\Services;

use Ramsey\Uuid\Uuid;

class BlockJsonService
{
    /**
     * Génère le manifest.json du behavior pack.
     */
    public function behaviorManifest(string $name): array
    {
        return [
            'format_version' => '1.0.0',
            'header' => [
                'name'        => $name . ' Behavior Pack',
                'version'     => '1.0.0',
                'description' => 'Behavior pack generated by Minecraft Block Generator',
            ],
            'metadata' => [
                'authors' => ['Minecraft Block Generator'],
            ],
        ];
    }

    /**
     * Génère le manifest.json du resource pack.
     */
    public function resourceManifest(string $name): array
    {
        return [
            'format_version' => 2,
            'metadata' => [
                'authors' => ['Minecraft Block Generator'],
            ],
            'header' => [
                'name'               => $name . ' Resource Pack',
                'description'        => 'Resource pack generated by Minecraft Block Generator',
                'uuid'               => Uuid::uuid4()->toString(),
                'version'            => [1, 0, 0],
                'min_engine_version' => [1, 21, 80],
            ],
            'modules' => [
                [
                    'type'    => 'resources',
                    'uuid'    => Uuid::uuid4()->toString(),
                    'version' => [1, 0, 0],
                ],
            ],
        ];
    }

    /**
     * Génère le fichier de comportement du bloc (behavior pack).
     */
    public function blockBehavior(string $identifier, bool $solid, bool $destructible, float $resistance, string $geometry = 'cube'): array
    {
        if ($geometry === 'net') {
            // Per-face textures from split net
            $materials = [
                'up'    => ['texture' => $identifier . '_top',    'render_method' => 'opaque'],
                'down'  => ['texture' => $identifier . '_bottom', 'render_method' => 'opaque'],
                'north' => ['texture' => $identifier . '_front',  'render_method' => 'opaque'],
                'south' => ['texture' => $identifier . '_back',   'render_method' => 'opaque'],
                'east'  => ['texture' => $identifier . '_right',  'render_method' => 'opaque'],
                'west'  => ['texture' => $identifier . '_left',   'render_method' => 'opaque'],
            ];
        } else {
            $renderMethod = $geometry === 'cross' ? 'alpha_test' : 'opaque';
            $materials = ['*' => ['texture' => $identifier, 'render_method' => $renderMethod]];
        }

        $components = [
            'minecraft:material_instances' => ['materials' => $materials],
            'minecraft:friction'             => 0.6,
            'minecraft:explosion_resistance' => $resistance,
        ];

        if ($geometry !== 'cube') {
            $components['minecraft:geometry'] = [
                'identifier' => 'geometry.' . $identifier,
            ];

            $box = $this->geometryBox($geometry);
            $components['minecraft:collision_box'] = $box ?? false;
            $components['minecraft:selection_box'] = $box ?? false;
        }

        if ($destructible) {
            $components['minecraft:destructible_by_mining'] = [
                'hardness' => max(0.05, $resistance / 20),
            ];
        }

        if (!$solid) {
            $components['minecraft:collision_box'] = false;
            $components['minecraft:selection_box'] = false;
        }

        return [
            'format_version' => '1.0.0',
            'minecraft:block' => [
                'description' => [
                    'identifier' => 'custom:' . $identifier,
                ],
                'components' => $components,
            ],
        ];
    }

    /**
     * Retourne la collision/selection box pour une forme donnée, ou null si aucune.
     */
    private function geometryBox(string $geometry): ?array
    {
        return match ($geometry) {
            'slab'   => ['origin' => [-8, 0, -8], 'size' => [16, 8, 16]],
            'plate'  => ['origin' => [-8, 0, -8], 'size' => [16, 2, 16]],
            'pillar' => ['origin' => [-2, 0, -2], 'size' => [4, 16, 4]],
            'cross'  => null,
            default  => null,
        };
    }

    /**
     * Génère le fichier de géométrie (.geo.json) pour une forme non-cubique.
     * Retourne un tableau vide si la forme est 'cube' (pas de géométrie nécessaire).
     */
    public function geometryJson(string $identifier, string $geometry): array
    {
        return match ($geometry) {
            'slab'   => $this->slabGeometry($identifier),
            'plate'  => $this->plateGeometry($identifier),
            'cross'  => $this->crossGeometry($identifier),
            'pillar' => $this->pillarGeometry($identifier),
            default  => [],
        };
    }

    private function slabGeometry(string $identifier): array
    {
        return [
            'format_version' => '1.12.0',
            'minecraft:geometry' => [
                [
                    'description' => [
                        'identifier'             => 'geometry.' . $identifier,
                        'texture_width'          => 16,
                        'texture_height'         => 16,
                        'visible_bounds_width'   => 2,
                        'visible_bounds_height'  => 1.5,
                        'visible_bounds_offset'  => [0, 0.25, 0],
                    ],
                    'bones' => [
                        [
                            'name'  => 'bb_main',
                            'pivot' => [0, 0, 0],
                            'cubes' => [
                                [
                                    'origin' => [-8, 0, -8],
                                    'size'   => [16, 8, 16],
                                    'uv'     => [
                                        'north' => ['uv' => [0, 0], 'uv_size' => [16, 8]],
                                        'east'  => ['uv' => [0, 0], 'uv_size' => [16, 8]],
                                        'south' => ['uv' => [0, 0], 'uv_size' => [16, 8]],
                                        'west'  => ['uv' => [0, 0], 'uv_size' => [16, 8]],
                                        'up'    => ['uv' => [0, 0], 'uv_size' => [16, 16]],
                                        'down'  => ['uv' => [0, 0], 'uv_size' => [16, 16]],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }

    private function plateGeometry(string $identifier): array
    {
        return [
            'format_version' => '1.12.0',
            'minecraft:geometry' => [
                [
                    'description' => [
                        'identifier'             => 'geometry.' . $identifier,
                        'texture_width'          => 16,
                        'texture_height'         => 16,
                        'visible_bounds_width'   => 2,
                        'visible_bounds_height'  => 1.5,
                        'visible_bounds_offset'  => [0, 0.125, 0],
                    ],
                    'bones' => [
                        [
                            'name'  => 'bb_main',
                            'pivot' => [0, 0, 0],
                            'cubes' => [
                                [
                                    'origin' => [-8, 0, -8],
                                    'size'   => [16, 2, 16],
                                    'uv'     => [
                                        'north' => ['uv' => [0, 0], 'uv_size' => [16, 2]],
                                        'east'  => ['uv' => [0, 0], 'uv_size' => [16, 2]],
                                        'south' => ['uv' => [0, 0], 'uv_size' => [16, 2]],
                                        'west'  => ['uv' => [0, 0], 'uv_size' => [16, 2]],
                                        'up'    => ['uv' => [0, 0], 'uv_size' => [16, 16]],
                                        'down'  => ['uv' => [0, 0], 'uv_size' => [16, 16]],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }

    private function crossGeometry(string $identifier): array
    {
        return [
            'format_version' => '1.12.0',
            'minecraft:geometry' => [
                [
                    'description' => [
                        'identifier'             => 'geometry.' . $identifier,
                        'texture_width'          => 16,
                        'texture_height'         => 16,
                        'visible_bounds_width'   => 2,
                        'visible_bounds_height'  => 2,
                        'visible_bounds_offset'  => [0, 0.5, 0],
                    ],
                    'bones' => [
                        [
                            'name'  => 'bb_main',
                            'pivot' => [0, 0, 0],
                            'cubes' => [
                                [
                                    'origin' => [-8, 0, 0],
                                    'size'   => [16, 16, 0],
                                    'uv'     => [
                                        'north' => ['uv' => [0, 0], 'uv_size' => [16, 16]],
                                        'south' => ['uv' => [0, 0], 'uv_size' => [16, 16]],
                                    ],
                                ],
                                [
                                    'origin' => [0, 0, -8],
                                    'size'   => [0, 16, 16],
                                    'uv'     => [
                                        'east' => ['uv' => [0, 0], 'uv_size' => [16, 16]],
                                        'west' => ['uv' => [0, 0], 'uv_size' => [16, 16]],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }

    private function pillarGeometry(string $identifier): array
    {
        return [
            'format_version' => '1.12.0',
            'minecraft:geometry' => [
                [
                    'description' => [
                        'identifier'             => 'geometry.' . $identifier,
                        'texture_width'          => 16,
                        'texture_height'         => 16,
                        'visible_bounds_width'   => 2,
                        'visible_bounds_height'  => 2,
                        'visible_bounds_offset'  => [0, 0.5, 0],
                    ],
                    'bones' => [
                        [
                            'name'  => 'bb_main',
                            'pivot' => [0, 0, 0],
                            'cubes' => [
                                [
                                    'origin' => [-2, 0, -2],
                                    'size'   => [4, 16, 4],
                                    'uv'     => [
                                        'north' => ['uv' => [6, 0], 'uv_size' => [4, 16]],
                                        'east'  => ['uv' => [6, 0], 'uv_size' => [4, 16]],
                                        'south' => ['uv' => [6, 0], 'uv_size' => [4, 16]],
                                        'west'  => ['uv' => [6, 0], 'uv_size' => [4, 16]],
                                        'up'    => ['uv' => [6, 6], 'uv_size' => [4, 4]],
                                        'down'  => ['uv' => [6, 6], 'uv_size' => [4, 4]],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }

    /**
     * Génère le terrain_texture.json du resource pack.
     */
    public function terrainTexture(string $identifier, string $geometry = 'cube'): array
    {
        if ($geometry === 'net') {
            $textureData = [];
            foreach (['top', 'bottom', 'front', 'back', 'left', 'right'] as $face) {
                $textureData["{$identifier}_{$face}"] = [
                    'textures' => "textures/blocks/{$identifier}_{$face}",
                ];
            }
        } else {
            $textureData = [
                $identifier => ['textures' => 'textures/blocks/' . $identifier],
            ];
        }

        return [
            'num_mip_levels'     => 4,
            'padding'            => 8,
            'resource_pack_name' => 'custom_blocks',
            'texture_name'       => 'atlas.terrain',
            'texture_data'       => $textureData,
        ];
    }

    /**
     * Génère le blocks.json du resource pack.
     */
    public function blocksJson(string $identifier): array
    {
        return [
            'format_version'        => '1.21.40',
            'custom:' . $identifier => [
                'sound'    => 'stone',
                'textures' => $identifier,
            ],
        ];
    }

    /**
     * Génère le contenu du fichier texts/en_US.lang.
     */
    public function textsLang(string $identifier, string $name): string
    {
        return "tile.custom:{$identifier}.name={$name}\n";
    }

    /**
     * Génère le languages.json du resource pack.
     */
    public function languagesJson(): array
    {
        return ['en_US'];
    }

    /**
     * Encode proprement en JSON (pretty print, unicode non échappé).
     */
    public function encode(array $data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }
}
