<?php

namespace App\Services;

use App\Models\Block;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use ZipArchive;

class BlockZipService
{
    public function __construct(private BlockJsonService $jsonService) {}

    public function generate(
        string       $name,
        string       $identifier,
        bool         $solid,
        bool         $destructible,
        float        $resistance,
        UploadedFile $texture,
        string       $geometry = 'cube',
        ?string      $customGeometryJson = null
    ): string {
        return $this->buildZip($name, $identifier, $solid, $destructible, $resistance, $texture->getRealPath(), $geometry, $customGeometryJson);
    }

    public function generateFromPath(
        string $name,
        string $identifier,
        bool   $solid,
        bool   $destructible,
        float  $resistance,
        string $texturePath,
        string $geometry = 'cube',
        ?string $customGeometryJson = null
    ): string {
        return $this->buildZip($name, $identifier, $solid, $destructible, $resistance, $texturePath, $geometry, $customGeometryJson);
    }

    /**
     * Generates a single merged pack ZIP for multiple blocks.
     *
     * @param Block[] $blocks
     */
    public function generateMulti(array $blocks): string
    {
        $zipPath = tempnam(sys_get_temp_dir(), 'mc_blocks_') . '.zip';

        $zip = new ZipArchive();
        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new \RuntimeException('Impossible de créer l\'archive ZIP.');
        }

        $root = 'custom_blocks_pack/';

        $zip->addEmptyDir($root . 'behavior_pack/');
        $zip->addEmptyDir($root . 'behavior_pack/blocks/');
        $zip->addFromString($root . 'behavior_pack/manifest.json',
            $this->jsonService->encode($this->jsonService->behaviorManifest('Custom Blocks'))
        );

        $zip->addEmptyDir($root . 'resource_pack/');
        $zip->addEmptyDir($root . 'resource_pack/textures/');
        $zip->addEmptyDir($root . 'resource_pack/textures/blocks/');
        $zip->addEmptyDir($root . 'resource_pack/texts/');
        $zip->addFromString($root . 'resource_pack/manifest.json',
            $this->jsonService->encode($this->jsonService->resourceManifest('Custom Blocks'))
        );

        $terrainData = [];
        $blocksJson  = ['format_version' => '1.21.40'];
        $langLines   = [
            'pack.name=Custom Blocks Resource Pack',
            'pack.description=Generated by Minecraft Block Generator',
        ];
        $tempFiles        = [];
        $hasCustomGeometry = false;

        foreach ($blocks as $block) {
            $identifier  = $block->identifier;
            $geometry    = $block->geometry ?? 'cube';
            $texturePath = Storage::path($block->texture_path);

            if (!file_exists($texturePath)) {
                continue;
            }

            // Behavior JSON (use stored custom geometry file if available)
            $customGeometryJson = $block->geometry_json_path ? Storage::get($block->geometry_json_path) : null;
            $blockJson = $customGeometryJson
                ? $customGeometryJson
                : $this->jsonService->encode(
                    $this->jsonService->blockBehavior($identifier, $block->solid, $block->destructible, $block->resistance, $geometry)
                );
            $zip->addFromString($root . 'behavior_pack/blocks/' . $identifier . '.json', $blockJson);

            // Textures
            if ($geometry === 'net') {
                $facePaths = $this->splitNetTexture($texturePath, $identifier);
                foreach ($facePaths as $face => $facePath) {
                    $zip->addFile($facePath, $root . "resource_pack/textures/blocks/{$identifier}_{$face}.png");
                    $tempFiles[] = $facePath;
                }
                foreach (['top', 'bottom', 'front', 'back', 'left', 'right'] as $face) {
                    $terrainData["{$identifier}_{$face}"] = ['textures' => "textures/blocks/{$identifier}_{$face}"];
                }
            } else {
                $zip->addFile($texturePath, $root . "resource_pack/textures/blocks/{$identifier}.png");
                $terrainData[$identifier] = ['textures' => "textures/blocks/{$identifier}"];
            }

            // blocks.json entry
            $blocksJson['custom:' . $identifier] = ['sound' => 'stone', 'textures' => $identifier];

            // lang entry
            $langLines[] = "tile.custom:{$identifier}.name={$block->name}";

            // Custom geometry file
            if ($geometry !== 'cube' && $geometry !== 'net' && $geometry !== 'glass') {
                if (!$hasCustomGeometry) {
                    $zip->addEmptyDir($root . 'resource_pack/models/');
                    $zip->addEmptyDir($root . 'resource_pack/models/blocks/');
                    $hasCustomGeometry = true;
                }
                $zip->addFromString(
                    $root . "resource_pack/models/blocks/{$identifier}.geo.json",
                    $this->jsonService->encode($this->jsonService->geometryJson($identifier, $geometry))
                );
            }
        }

        $zip->addFromString($root . 'resource_pack/terrain_texture.json',
            $this->jsonService->encode([
                'num_mip_levels'     => 4,
                'padding'            => 8,
                'resource_pack_name' => 'custom_blocks',
                'texture_name'       => 'atlas.terrain',
                'texture_data'       => $terrainData,
            ])
        );
        $zip->addFromString($root . 'resource_pack/blocks.json', $this->jsonService->encode($blocksJson));
        $zip->addFromString($root . 'resource_pack/texts/en_US.lang', implode("\n", $langLines) . "\n");
        $zip->addFromString($root . 'resource_pack/texts/languages.json', $this->jsonService->encode(['en_US']));

        $zip->close();

        register_shutdown_function(static function () use ($tempFiles) {
            foreach ($tempFiles as $path) {
                if (file_exists($path)) {
                    unlink($path);
                }
            }
        });

        return $zipPath;
    }

    private function buildZip(
        string $name,
        string $identifier,
        bool   $solid,
        bool   $destructible,
        float  $resistance,
        string $texturePath,
        string $geometry = 'cube',
        ?string $customGeometryJson = null
    ): string {
        $zipPath = tempnam(sys_get_temp_dir(), 'mc_block_') . '.zip';

        $zip = new ZipArchive();
        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new \RuntimeException('Impossible de créer l\'archive ZIP.');
        }

        $root = 'generated_pack/';

        // --- Behavior Pack ---
        $zip->addEmptyDir($root . 'behavior_pack/');
        $zip->addEmptyDir($root . 'behavior_pack/blocks/');

        $zip->addFromString(
            $root . 'behavior_pack/manifest.json',
            $this->jsonService->encode($this->jsonService->behaviorManifest($name))
        );

        // Utiliser le fichier géométrie personnalisée si fourni, sinon générer le comportement
        if ($customGeometryJson) {
            $zip->addFromString(
                $root . 'behavior_pack/blocks/' . $identifier . '.json',
                $customGeometryJson
            );
        } else {
            $zip->addFromString(
                $root . 'behavior_pack/blocks/' . $identifier . '.json',
                $this->jsonService->encode(
                    $this->jsonService->blockBehavior($identifier, $solid, $destructible, $resistance, $geometry)
                )
            );
        }

        // --- Resource Pack ---
        $zip->addEmptyDir($root . 'resource_pack/');
        $zip->addEmptyDir($root . 'resource_pack/textures/');
        $zip->addEmptyDir($root . 'resource_pack/textures/blocks/');
        $zip->addEmptyDir($root . 'resource_pack/texts/');

        $zip->addFromString(
            $root . 'resource_pack/manifest.json',
            $this->jsonService->encode($this->jsonService->resourceManifest($name))
        );

        $zip->addFromString(
            $root . 'resource_pack/terrain_texture.json',
            $this->jsonService->encode($this->jsonService->terrainTexture($identifier, $geometry))
        );

        $zip->addFromString(
            $root . 'resource_pack/blocks.json',
            $this->jsonService->encode($this->jsonService->blocksJson($identifier))
        );

        $zip->addFromString(
            $root . 'resource_pack/texts/languages.json',
            $this->jsonService->encode($this->jsonService->languagesJson())
        );

        $zip->addFromString(
            $root . 'resource_pack/texts/en_US.lang',
            $this->jsonService->textsLang($identifier, $name)
        );

        // Textures: split net into 6 faces, or add single texture
        if ($geometry === 'net') {
            $facePaths = $this->splitNetTexture($texturePath, $identifier);
            foreach ($facePaths as $face => $facePath) {
                $zip->addFile($facePath, $root . "resource_pack/textures/blocks/{$identifier}_{$face}.png");
            }
            // Clean up temp face files after ZIP is closed
            register_shutdown_function(static function () use ($facePaths) {
                foreach ($facePaths as $path) {
                    if (file_exists($path)) {
                        unlink($path);
                    }
                }
            });
        } else {
            $zip->addFile($texturePath, $root . 'resource_pack/textures/blocks/' . $identifier . '.png');
        }

        // Geometry file for non-cube, non-net, non-glass shapes (slab, pillar, plate, cross)
        if ($geometry !== 'cube' && $geometry !== 'net' && $geometry !== 'glass') {
            $zip->addEmptyDir($root . 'resource_pack/models/');
            $zip->addEmptyDir($root . 'resource_pack/models/blocks/');
            $zip->addFromString(
                $root . 'resource_pack/models/blocks/' . $identifier . '.geo.json',
                $this->jsonService->encode($this->jsonService->geometryJson($identifier, $geometry))
            );
        }

        $zip->close();

        return $zipPath;
    }

    /**
     * Découpe une texture en réseau 4:3 (croix dépliée) en 6 faces PNG temporaires.
     *
     * Layout standard (width=4C, height=3C):
     *        [top]
     *  [left][front][right][back]
     *        [bottom]
     */
    private function splitNetTexture(string $texturePath, string $identifier): array
    {
        $img = imagecreatefrompng($texturePath);
        $w   = imagesx($img);
        $C   = intval($w / 4);

        $regions = [
            'top'    => [$C,       0],
            'left'   => [0,        $C],
            'front'  => [$C,       $C],
            'right'  => [2 * $C,   $C],
            'back'   => [3 * $C,   $C],
            'bottom' => [$C,       2 * $C],
        ];

        $paths = [];
        foreach ($regions as $face => [$sx, $sy]) {
            $faceImg = imagecreatetruecolor($C, $C);
            imagealphablending($faceImg, false);
            imagesavealpha($faceImg, true);
            imagecopy($faceImg, $img, 0, 0, $sx, $sy, $C, $C);

            $facePath = tempnam(sys_get_temp_dir(), "mc_{$identifier}_{$face}_") . '.png';
            imagepng($faceImg, $facePath);
            imagedestroy($faceImg);
            $paths[$face] = $facePath;
        }

        imagedestroy($img);
        return $paths;
    }
}
