<?php

namespace App\Services;

use Ramsey\Uuid\Uuid;

class BlockJsonService
{
    /**
     * Génère le manifest.json du behavior pack.
     */
    public function behaviorManifest(string $name): array
    {
        return [
            'format_version' => 2,
            'header' => [
                'name'        => $name . ' Behavior Pack',
                'description' => 'Behavior pack generated by Minecraft Block Generator',
                'uuid'        => Uuid::uuid4()->toString(),
                'version'     => [1, 0, 0],
                'min_engine_version' => [1, 16, 0],
            ],
            'modules' => [
                [
                    'type'        => 'data',
                    'uuid'        => Uuid::uuid4()->toString(),
                    'version'     => [1, 0, 0],
                ],
            ],
        ];
    }

    /**
     * Génère le manifest.json du resource pack.
     */
    public function resourceManifest(string $name): array
    {
        return [
            'format_version' => 2,
            'header' => [
                'name'        => $name . ' Resource Pack',
                'description' => 'Resource pack generated by Minecraft Block Generator',
                'uuid'        => Uuid::uuid4()->toString(),
                'version'     => [1, 0, 0],
                'min_engine_version' => [1, 16, 0],
            ],
            'modules' => [
                [
                    'type'        => 'resources',
                    'uuid'        => Uuid::uuid4()->toString(),
                    'version'     => [1, 0, 0],
                ],
            ],
        ];
    }

    /**
     * Génère le fichier de comportement du bloc (behavior pack).
     */
    public function blockBehavior(string $identifier, bool $solid, bool $destructible, float $resistance): array
    {
        $components = [
            'minecraft:friction'            => 0.6,
            'minecraft:explosion_resistance'=> $resistance,
        ];

        if ($destructible) {
            $components['minecraft:destroy_time'] = max(0.05, $resistance / 20);
        } else {
            // Temps de destruction très élevé = indestructible
            $components['minecraft:destroy_time'] = -1;
        }

        if (!$solid) {
            $components['minecraft:collision_box'] = false;
            $components['minecraft:selection_box'] = false;
        }

        return [
            'format_version' => '1.16.0',
            'minecraft:block' => [
                'description' => [
                    'identifier' => 'custom:' . $identifier,
                ],
                'components' => $components,
            ],
        ];
    }

    /**
     * Génère le terrain_texture.json du resource pack.
     */
    public function terrainTexture(string $identifier): array
    {
        return [
            'resource_pack_name' => 'custom_blocks',
            'texture_name'       => 'atlas.terrain',
            'texture_data'       => [
                'custom_' . $identifier => [
                    'textures' => 'textures/blocks/' . $identifier,
                ],
            ],
        ];
    }

    /**
     * Encode proprement en JSON (pretty print, unicode non échappé).
     */
    public function encode(array $data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }
}
