<?php

namespace App\Services;

use Ramsey\Uuid\Uuid;

class BlockJsonService
{
    /**
     * Génère le manifest.json du behavior pack.
     */
    public function behaviorManifest(string $name): array
    {
        return [
            'format_version' => '1.0.0',
            'header' => [
                'name'        => $name . ' Behavior Pack',
                'version'     => '1.0.0',
                'description' => 'Behavior pack generated by Minecraft Block Generator',
            ],
            'metadata' => [
                'authors' => ['Minecraft Block Generator'],
            ],
        ];
    }

    /**
     * Génère le manifest.json du resource pack.
     */
    public function resourceManifest(string $name): array
    {
        return [
            'format_version' => 2,
            'metadata' => [
                'authors' => ['Minecraft Block Generator'],
            ],
            'header' => [
                'name'               => $name . ' Resource Pack',
                'description'        => 'Resource pack generated by Minecraft Block Generator',
                'uuid'               => Uuid::uuid4()->toString(),
                'version'            => [1, 0, 0],
                'min_engine_version' => [1, 21, 80],
            ],
            'modules' => [
                [
                    'type'    => 'resources',
                    'uuid'    => Uuid::uuid4()->toString(),
                    'version' => [1, 0, 0],
                ],
            ],
        ];
    }

    /**
     * Génère le fichier de comportement du bloc (behavior pack).
     */
    public function blockBehavior(string $identifier, bool $solid, bool $destructible, float $resistance): array
    {
        $components = [
            'minecraft:material_instances' => [
                'materials' => [
                    '*' => [
                        'texture'       => $identifier,
                        'render_method' => 'blend',
                    ],
                ],
            ],
            'minecraft:friction'             => 0.6,
            'minecraft:explosion_resistance' => $resistance,
        ];

        if ($destructible) {
            $components['minecraft:destructible_by_mining'] = [
                'hardness' => max(0.05, $resistance / 20),
            ];
        }
        // Absence de minecraft:destructible_by_mining = indestructible

        if (!$solid) {
            $components['minecraft:collision_box'] = false;
            $components['minecraft:selection_box'] = false;
        }

        return [
            'format_version' => '1.0.0',
            'minecraft:block' => [
                'description' => [
                    'identifier' => 'custom:' . $identifier,
                ],
                'components' => $components,
            ],
        ];
    }

    /**
     * Génère le terrain_texture.json du resource pack.
     */
    public function terrainTexture(string $identifier): array
    {
        return [
            'num_mip_levels'     => 4,
            'padding'            => 8,
            'resource_pack_name' => 'custom_blocks',
            'texture_name'       => 'atlas.terrain',
            'texture_data'       => [
                $identifier => [
                    'textures' => 'textures/blocks/' . $identifier,
                ],
            ],
        ];
    }

    /**
     * Génère le blocks.json du resource pack.
     */
    public function blocksJson(string $identifier): array
    {
        return [
            'format_version'        => '1.21.40',
            'custom:' . $identifier => [
                'sound'    => 'stone',
                'textures' => $identifier,
            ],
        ];
    }

    /**
     * Génère le contenu du fichier texts/en_US.lang.
     */
    public function textsLang(string $identifier, string $name): string
    {
        return "tile.custom:{$identifier}.name={$name}\n";
    }

    /**
     * Génère le languages.json du resource pack.
     */
    public function languagesJson(): array
    {
        return ['en_US'];
    }

    /**
     * Encode proprement en JSON (pretty print, unicode non échappé).
     */
    public function encode(array $data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }
}
