<?php

namespace App\Services;

use Ramsey\Uuid\Uuid;

class ItemJsonService
{
    public function behaviorManifest(string $name): array
    {
        return [
            'format_version' => 2,
            'header' => [
                'name'               => $name . ' Behavior Pack',
                'description'        => 'Behavior pack generated by Minecraft Block Generator',
                'uuid'               => Uuid::uuid4()->toString(),
                'version'            => [1, 0, 0],
                'min_engine_version' => [1, 21, 80],
            ],
            'modules' => [
                [
                    'type'    => 'data',
                    'uuid'    => Uuid::uuid4()->toString(),
                    'version' => [1, 0, 0],
                ],
            ],
            'metadata' => [
                'authors' => ['Minecraft Block Generator'],
            ],
        ];
    }

    public function resourceManifest(string $name): array
    {
        return [
            'format_version' => 2,
            'metadata' => [
                'authors' => ['Minecraft Block Generator'],
            ],
            'header' => [
                'name'               => $name . ' Resource Pack',
                'description'        => 'Resource pack generated by Minecraft Block Generator',
                'uuid'               => Uuid::uuid4()->toString(),
                'version'            => [1, 0, 0],
                'min_engine_version' => [1, 21, 80],
            ],
            'modules' => [
                [
                    'type'    => 'resources',
                    'uuid'    => Uuid::uuid4()->toString(),
                    'version' => [1, 0, 0],
                ],
            ],
        ];
    }

    public function itemBehavior(
        string $identifier,
        ?int $maxStackSize = null,
        ?int $maxDurability = null,
        ?int $itemTier = null,
        ?float $itemMultiplier = null,
        ?int $damage = null,
        ?bool $handEquipped = null,
    ): array {
        $components = [
            'minecraft:display_name' => [
                'value' => '§r' . $identifier,
            ],
        ];

        if ($maxStackSize !== null) {
            $components['minecraft:max_stack_size'] = ['value' => $maxStackSize];
        }

        if ($maxDurability !== null) {
            $components['minecraft:durability'] = ['max_durability' => $maxDurability];
        }

        if ($itemTier !== null && $itemMultiplier !== null) {
            $components['minecraft:axe'] = [
                'tier' => $itemTier,
                'multiplier' => $itemMultiplier,
            ];
        }

        if ($damage !== null && $damage > 0) {
            $components['minecraft:damage'] = ['damage' => $damage];
        }

        if ($handEquipped === true) {
            $components['minecraft:hand_equipped'] = ['enabled' => true];
        }

        return [
            'format_version' => '1.16.100',
            'minecraft:item' => [
                'description' => [
                    'identifier' => 'custom:' . $identifier,
                    'category'   => 'equipment',
                ],
                'components' => $components,
            ],
        ];
    }

    public function itemTexture(string $identifier): array
    {
        return [
            'resource_pack_name' => 'custom_items',
            'texture_name'       => 'atlas.items',
            'texture_data'       => [
                'custom:' . $identifier => [
                    'textures' => 'textures/items/' . $identifier,
                ],
            ],
        ];
    }

    public function itemsJson(string $identifier): array
    {
        return [
            'format_version' => '1.21.40',
            'custom:' . $identifier => [
                'textures' => 'custom:' . $identifier,
            ],
        ];
    }

    public function languagesJson(): array
    {
        return ['en_US'];
    }

    public function textsLang(string $identifier, string $name): string
    {
        return "pack.name=Custom Items Resource Pack\npack.description=Generated by Minecraft Block Generator\nitem.custom:{$identifier}.name={$name}\n";
    }

    public function encode(array $data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }
}
