<?php

namespace App\Services;

use Ramsey\Uuid\Uuid;

class MobJsonService
{
    public function encode(mixed $data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }

    public function behaviorManifest(string $name): array
    {
        return [
            'format_version' => 2,
            'header' => [
                'name'              => $name . ' Behavior Pack',
                'description'       => 'Generated by Minecraft Mob Generator',
                'uuid'              => Uuid::uuid4()->toString(),
                'version'           => [1, 0, 0],
                'min_engine_version'=> [1, 21, 0],
            ],
            'modules' => [[
                'type'        => 'data',
                'uuid'        => Uuid::uuid4()->toString(),
                'version'     => [1, 0, 0],
            ]],
        ];
    }

    public function resourceManifest(string $name): array
    {
        return [
            'format_version' => 2,
            'header' => [
                'name'              => $name . ' Resource Pack',
                'description'       => 'Generated by Minecraft Mob Generator',
                'uuid'              => Uuid::uuid4()->toString(),
                'version'           => [1, 0, 0],
                'min_engine_version'=> [1, 21, 0],
            ],
            'modules' => [[
                'type'    => 'resources',
                'uuid'    => Uuid::uuid4()->toString(),
                'version' => [1, 0, 0],
            ]],
        ];
    }

    public function entityBehavior(
        string $identifier,
        int    $health,
        float  $speed,
        string $behaviorType,
        ?int   $attackDamage,
        bool   $isSpawnable,
        bool   $isSummonable,
        float  $collisionWidth,
        float  $collisionHeight
    ): array {
        $components = [
            'minecraft:health'        => ['value' => $health, 'max' => $health],
            'minecraft:movement'      => ['value' => $speed],
            'minecraft:physics'       => (object)[],
            'minecraft:jump.basic'    => (object)[],
            'minecraft:navigation.walk' => ['can_path_over_water' => true],
            'minecraft:collision_box' => ['width' => $collisionWidth, 'height' => $collisionHeight],
            'minecraft:behavior.random_stroll'    => ['priority' => 7, 'speed_multiplier' => 1.0],
            'minecraft:behavior.look_at_player'   => ['priority' => 8, 'look_distance' => 8.0],
            'minecraft:behavior.random_look_around' => ['priority' => 9],
        ];

        if ($behaviorType === 'hostile' || $behaviorType === 'neutral') {
            $damage = $attackDamage ?? 3;
            $components['minecraft:attack'] = ['damage' => $damage];
            $components['minecraft:behavior.melee_attack'] = ['priority' => 3, 'speed_multiplier' => 1.0];
            $components['minecraft:behavior.hurt_by_target'] = ['priority' => 1];
        }

        if ($behaviorType === 'hostile') {
            $components['minecraft:behavior.nearest_attackable_target'] = [
                'priority'    => 2,
                'entity_types'=> [['filters' => ['test' => 'is_family', 'subject' => 'other', 'value' => 'player'], 'max_dist' => 16]],
            ];
        }

        return [
            'format_version' => '1.21.0',
            'minecraft:entity' => [
                'description' => [
                    'identifier'    => 'custom:' . $identifier,
                    'is_spawnable'  => $isSpawnable,
                    'is_summonable' => $isSummonable,
                    'is_experimental' => false,
                ],
                'component_groups' => (object)[],
                'components'       => $components,
                'events'           => (object)[],
            ],
        ];
    }

    public function clientEntity(string $identifier, string $modelType, string $primaryColor, string $secondaryColor): array
    {
        return [
            'format_version' => '1.10.0',
            'minecraft:client_entity' => [
                'description' => [
                    'identifier'        => 'custom:' . $identifier,
                    'materials'         => ['default' => 'entity_alphatest'],
                    'textures'          => ['default' => 'textures/entity/' . $identifier],
                    'geometry'          => ['default' => 'geometry.' . $identifier],
                    'render_controllers'=> ['controller.render.' . $identifier],
                    'spawn_egg'         => [
                        'base_color'    => $primaryColor,
                        'overlay_color' => $secondaryColor,
                    ],
                ],
            ],
        ];
    }

    public function renderController(string $identifier): array
    {
        return [
            'format_version' => '1.8.0',
            'render_controllers' => [
                'controller.render.' . $identifier => [
                    'geometry'  => 'Geometry.default',
                    'materials' => [['*' => 'Material.default']],
                    'textures'  => ['Texture.default'],
                ],
            ],
        ];
    }

    public function geometryJson(string $identifier, string $modelType): array
    {
        $bones = match ($modelType) {
            'quadruped' => $this->quadrupedBones(),
            'creeper'   => $this->creeperBones(),
            default     => $this->humanoidBones(),
        };

        [$tw, $th, $bw, $bh, $offset] = match ($modelType) {
            'quadruped' => [64, 32, 2.0, 2.0,   [0, 0.75, 0]],
            'creeper'   => [64, 32, 1.5, 1.5,   [0, 0.75, 0]],
            default     => [64, 64, 2.0, 2.5,   [0, 1.0,  0]],
        };

        return [
            'format_version' => '1.12.0',
            'minecraft:geometry' => [[
                'description' => [
                    'identifier'           => 'geometry.' . $identifier,
                    'texture_width'        => $tw,
                    'texture_height'       => $th,
                    'visible_bounds_width' => $bw,
                    'visible_bounds_height'=> $bh,
                    'visible_bounds_offset'=> $offset,
                ],
                'bones' => $bones,
            ]],
        ];
    }

    private function humanoidBones(): array
    {
        return [
            ['name' => 'root',  'pivot' => [0, 0, 0]],
            ['name' => 'waist', 'parent' => 'root', 'pivot' => [0, 12, 0]],
            [
                'name' => 'body', 'parent' => 'waist', 'pivot' => [0, 24, 0],
                'cubes' => [['origin' => [-4, 12, -2], 'size' => [8, 12, 4], 'uv' => [16, 16]]],
            ],
            [
                'name' => 'head', 'parent' => 'body', 'pivot' => [0, 24, 0],
                'cubes' => [['origin' => [-4, 24, -4], 'size' => [8, 8, 8], 'uv' => [0, 0]]],
            ],
            [
                'name' => 'hat', 'parent' => 'body', 'pivot' => [0, 24, 0],
                'cubes' => [['origin' => [-4, 24, -4], 'size' => [8, 8, 8], 'uv' => [32, 0], 'inflate' => 0.5]],
            ],
            [
                'name' => 'rightArm', 'parent' => 'body', 'pivot' => [-5, 22, 0],
                'cubes' => [['origin' => [-8, 12, -2], 'size' => [4, 12, 4], 'uv' => [40, 16]]],
            ],
            [
                'name' => 'leftArm', 'parent' => 'body', 'pivot' => [5, 22, 0],
                'cubes' => [['origin' => [4, 12, -2], 'size' => [4, 12, 4], 'uv' => [32, 48]]],
            ],
            [
                'name' => 'rightLeg', 'parent' => 'root', 'pivot' => [-1.9, 12, 0],
                'cubes' => [['origin' => [-3.9, 0, -2], 'size' => [4, 12, 4], 'uv' => [0, 16]]],
            ],
            [
                'name' => 'leftLeg', 'parent' => 'root', 'pivot' => [1.9, 12, 0],
                'cubes' => [['origin' => [-0.1, 0, -2], 'size' => [4, 12, 4], 'uv' => [16, 48]]],
            ],
        ];
    }

    private function quadrupedBones(): array
    {
        return [
            ['name' => 'root', 'pivot' => [0, 0, 0]],
            [
                'name' => 'body', 'parent' => 'root', 'pivot' => [0, 10, 0],
                'cubes' => [['origin' => [-5, 6, -8], 'size' => [10, 8, 16], 'uv' => [0, 0]]],
            ],
            [
                'name' => 'head', 'parent' => 'body', 'pivot' => [0, 12, -8],
                'cubes' => [['origin' => [-4, 8, -14], 'size' => [8, 8, 8], 'uv' => [0, 16]]],
            ],
            [
                'name' => 'legFrontRight', 'parent' => 'body', 'pivot' => [-3, 6, -5],
                'cubes' => [['origin' => [-5, 0, -7], 'size' => [4, 6, 4], 'uv' => [16, 0]]],
            ],
            [
                'name' => 'legFrontLeft', 'parent' => 'body', 'pivot' => [3, 6, -5],
                'cubes' => [['origin' => [1, 0, -7], 'size' => [4, 6, 4], 'uv' => [16, 0]]],
            ],
            [
                'name' => 'legBackRight', 'parent' => 'body', 'pivot' => [-3, 6, 5],
                'cubes' => [['origin' => [-5, 0, 3], 'size' => [4, 6, 4], 'uv' => [16, 0]]],
            ],
            [
                'name' => 'legBackLeft', 'parent' => 'body', 'pivot' => [3, 6, 5],
                'cubes' => [['origin' => [1, 0, 3], 'size' => [4, 6, 4], 'uv' => [16, 0]]],
            ],
        ];
    }

    private function creeperBones(): array
    {
        return [
            ['name' => 'root', 'pivot' => [0, 0, 0]],
            [
                'name' => 'body', 'parent' => 'root', 'pivot' => [0, 6, 0],
                'cubes' => [['origin' => [-4, 6, -2], 'size' => [8, 12, 4], 'uv' => [16, 16]]],
            ],
            [
                'name' => 'head', 'parent' => 'body', 'pivot' => [0, 18, 0],
                'cubes' => [['origin' => [-4, 18, -4], 'size' => [8, 8, 8], 'uv' => [0, 0]]],
            ],
            [
                'name' => 'leg0', 'parent' => 'root', 'pivot' => [-2, 6, -2],
                'cubes' => [['origin' => [-4, 0, -4], 'size' => [4, 6, 4], 'uv' => [0, 16]]],
            ],
            [
                'name' => 'leg1', 'parent' => 'root', 'pivot' => [2, 6, -2],
                'cubes' => [['origin' => [0, 0, -4], 'size' => [4, 6, 4], 'uv' => [0, 16]]],
            ],
            [
                'name' => 'leg2', 'parent' => 'root', 'pivot' => [-2, 6, 2],
                'cubes' => [['origin' => [-4, 0, 0], 'size' => [4, 6, 4], 'uv' => [0, 16]]],
            ],
            [
                'name' => 'leg3', 'parent' => 'root', 'pivot' => [2, 6, 2],
                'cubes' => [['origin' => [0, 0, 0], 'size' => [4, 6, 4], 'uv' => [0, 16]]],
            ],
        ];
    }

    public function animationController(string $identifier, string $modelType): array
    {
        $baseAnim = match ($modelType) {
            'quadruped' => 'animation.pig.walk',
            'creeper'   => 'animation.creeper.walk',
            default     => 'animation.humanoid.base_pose',
        };

        return [
            'format_version' => '1.10.0',
            'animation_controllers' => [
                'controller.animation.' . $identifier . '.general' => [
                    'initial_state' => 'default',
                    'states' => [
                        'default' => [
                            'animations' => [$baseAnim],
                        ],
                    ],
                ],
            ],
        ];
    }

    public function textsLang(string $identifier, string $name): string
    {
        return implode("\n", [
            'pack.name=' . $name . ' Resource Pack',
            'pack.description=Generated by Minecraft Mob Generator',
            'entity.custom:' . $identifier . '.name=' . $name,
        ]) . "\n";
    }
}
